import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shaun Carr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center h-screen">
        <h1 className="font-extrabold text-8xl text-fuchsia-600">
          Hello Im Shaun!
        </h1>
        <p className="text-lg">welcome to my web garden 🌱</p>
      </main>
    </div>
  );
}
