import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Shaun Carr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full flex-col justify-center items-center text-center">
        <h1 className="font-bold text-7xl text-fuchsia-600">
          hello i&apos;m shaun.
        </h1>
        <p className="text-xl mt-16">welcome to my web garden 🌱</p>
      </main>
    </div>
  );
}
